"""Database models using SQLAlchemy ORM.

This module contains all database models for the application.
Models inherit from Base (defined in database.py) and represent
database tables using SQLAlchemy's declarative syntax.

All models are designed for Supabase PostgreSQL.
"""
from datetime import datetime
from enum import Enum as PyEnum

from sqlalchemy import Column, Integer, String, Text, DateTime, Boolean, ForeignKey, Float, Index
from sqlalchemy.orm import relationship

from app.database import Base


class Conversation(Base):
    """
    Conversation model for storing user-bot interactions.

    This model stores complete conversation records including:
    - User messages and bot replies
    - Channel/platform information
    - Detected intent
    - Timestamp for each conversation
    - Business/workspace association (multi-tenant)

    Table: conversations
    """

    __tablename__ = "conversations"

    # Primary key - auto-incrementing integer
    id = Column(Integer, primary_key=True, index=True)

    # Business/Workspace - links conversation to a specific business (multi-tenant)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)

    # User identifier - platform-specific user ID (e.g., Telegram user ID)
    # Stored as string to support different platform ID formats
    user_id = Column(String, nullable=False, index=True)

    # Channel/platform - messaging platform (telegram, whatsapp, instagram)
    # Stored as string matching MessageChannel enum values
    channel = Column(String, nullable=False, index=True)

    # User message - the original message from the user
    # Using Text type to support long messages
    user_message = Column(Text, nullable=False)

    # Bot reply - the response generated by the AI brain
    # Using Text type to support long responses
    bot_reply = Column(Text, nullable=False)

    # Intent - detected intent from the message (greeting, help, pricing, etc.)
    # Stored as string matching Intent enum values from ai_brain.py
    intent = Column(String, nullable=False, index=True)

    # Created timestamp - when the conversation was recorded
    # Automatically set to current UTC time when record is created
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)


class User(Base):
    """
    User model for authentication and access control.

    Supports multiple roles: Admin, Business Owner, Agent
    Admin users don't need a business_id (platform-level access)
    Business owners and agents are linked to a business (multi-tenant)
    """
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    email = Column(String, unique=True, index=True, nullable=False)
    hashed_password = Column(String, nullable=False)
    full_name = Column(String, nullable=True)
    role = Column(String, nullable=False, default="agent")  # admin, business_owner, agent
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=True, index=True)  # Nullable for admin users
    is_active = Column(Boolean, default=True, nullable=False)
    
    # Billing fields
    trial_ends_at = Column(DateTime, nullable=True)  # Trial end date
    
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)
    
    # Relationships
    billing_events = relationship("BillingEvent", back_populates="user")


class Business(Base):
    """
    Business/Workspace model for multi-tenant support.
    """
    __tablename__ = "businesses"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, nullable=False, index=True)
    owner_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    settings = Column(Text, nullable=True)  # JSON string for flexible settings
    
    # Billing fields
    stripe_customer_id = Column(String(255), unique=True, nullable=True, index=True)
    payment_status = Column(String(20), default="active")  # active, past_due, suspended
    
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)
    
    # Relationships
    subscription = relationship("Subscription", back_populates="business", uselist=False)
    invoices = relationship("Invoice", back_populates="business")
    payments = relationship("Payment", back_populates="business")
    payment_methods = relationship("PaymentMethod", back_populates="business")
    usage_records = relationship("UsageRecord", back_populates="business")
    billing_events = relationship("BillingEvent", back_populates="business")


class ChannelIntegration(Base):
    """
    Channel integration model for managing platform connections.
    """
    __tablename__ = "channel_integrations"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    channel = Column(String, nullable=False, index=True)  # telegram, whatsapp, instagram, etc.
    channel_name = Column(String, nullable=True)  # Custom name for the integration
    credentials = Column(Text, nullable=True)  # Encrypted JSON credentials
    is_active = Column(Boolean, default=True, nullable=False)
    webhook_url = Column(String, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


class Message(Base):
    """
    Individual message model for detailed conversation tracking.
    """
    __tablename__ = "messages"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)  # Multi-tenant support
    conversation_id = Column(Integer, ForeignKey("conversations.id"), nullable=True, index=True)
    user_id = Column(String, nullable=False, index=True)
    channel = Column(String, nullable=False, index=True)
    message_text = Column(Text, nullable=False)
    is_from_user = Column(Boolean, nullable=False)  # True = user message, False = bot reply
    intent = Column(String, nullable=True, index=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)


class Lead(Base):
    """
    Lead model for capturing and tracking potential customers.
    """
    __tablename__ = "leads"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    user_id = Column(String, nullable=False, index=True)
    channel = Column(String, nullable=False, index=True)
    name = Column(String, nullable=True)
    email = Column(String, nullable=True, index=True)
    phone = Column(String, nullable=True)
    status = Column(String, default="new", nullable=False, index=True)  # new, contacted, qualified, converted
    source_intent = Column(String, nullable=True)  # Intent that triggered lead capture
    extra_data = Column(Text, nullable=True)  # JSON string for additional data (renamed from metadata - SQLAlchemy reserved)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


class KnowledgeEntry(Base):
    """
    Knowledge base entry model for FAQs and documents.
    """
    __tablename__ = "knowledge_entries"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    question = Column(Text, nullable=False)
    answer = Column(Text, nullable=False)
    keywords = Column(Text, nullable=True)  # JSON array of keywords
    intent = Column(String, nullable=True, index=True)  # Associated intent
    is_active = Column(Boolean, default=True, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


class ConversationMemory(Base):
    """
    Conversation memory model for tracking user context.
    """
    __tablename__ = "conversation_memory"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)  # Multi-tenant support
    user_id = Column(String, nullable=False, index=True)
    channel = Column(String, nullable=False, index=True)
    last_intent = Column(String, nullable=True)
    message_count = Column(Integer, default=0, nullable=False)
    context_data = Column(Text, nullable=True)  # JSON string for additional context
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


class AnalyticsEvent(Base):
    """
    Analytics event model for tracking system events.
    """
    __tablename__ = "analytics_events"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=True, index=True)
    event_type = Column(String, nullable=False, index=True)  # conversation_started, intent_detected, etc.
    event_data = Column(Text, nullable=True)  # JSON string for event details
    channel = Column(String, nullable=True, index=True)
    user_id = Column(String, nullable=True, index=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)


class AdAsset(Base):
    """
    Ad and video creation asset model.
    """
    __tablename__ = "ad_assets"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    asset_type = Column(String, nullable=False)  # ad_copy, video, image
    title = Column(String, nullable=False)
    content = Column(Text, nullable=True)  # Ad copy text or video/image metadata
    platform = Column(String, nullable=True)  # instagram, whatsapp, facebook
    status = Column(String, default="draft", nullable=False)  # draft, published, archived
    extra_data = Column(Text, nullable=True)  # JSON string for additional data (renamed from metadata - SQLAlchemy reserved)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


# ========== USERS & ROLES MODELS ==========

class Role(Base):
    """
    Role model for RBAC (Role-Based Access Control).
    """
    __tablename__ = "roles"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=True, index=True)  # Nullable for system roles
    name = Column(String, nullable=False, index=True)  # owner, admin, agent, viewer, custom
    description = Column(Text, nullable=True)
    is_system = Column(Boolean, default=False, nullable=False)  # System roles cannot be deleted
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


class Permission(Base):
    """
    Permission model for granular access control.
    """
    __tablename__ = "permissions"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, unique=True, nullable=False, index=True)  # e.g., "conversations.view", "users.manage"
    description = Column(Text, nullable=True)
    category = Column(String, nullable=True, index=True)  # conversations, users, settings, etc.
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)


class RolePermission(Base):
    """
    Many-to-many relationship between roles and permissions.
    """
    __tablename__ = "role_permissions"

    id = Column(Integer, primary_key=True, index=True)
    role_id = Column(Integer, ForeignKey("roles.id"), nullable=False, index=True)
    permission_id = Column(Integer, ForeignKey("permissions.id"), nullable=False, index=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)


class UserRole(Base):
    """
    Many-to-many relationship between users and roles.
    """
    __tablename__ = "user_roles"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    role_id = Column(Integer, ForeignKey("roles.id"), nullable=False, index=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)


# ========== HANDOFF MODELS ==========

class Handoff(Base):
    """
    Handoff model for AI-to-human conversation transitions.
    """
    __tablename__ = "handoffs"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    conversation_id = Column(Integer, ForeignKey("conversations.id"), nullable=False, index=True)
    assigned_to_user_id = Column(Integer, ForeignKey("users.id"), nullable=True, index=True)
    status = Column(String, default="pending", nullable=False, index=True)  # pending, assigned, in_progress, resolved
    priority = Column(String, default="medium", nullable=False, index=True)  # low, medium, high, urgent
    reason = Column(Text, nullable=True)  # Why handoff was triggered
    assigned_at = Column(DateTime, nullable=True)
    resolved_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


class SLA(Base):
    """
    SLA (Service Level Agreement) model for tracking response and resolution times.
    """
    __tablename__ = "slas"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    handoff_id = Column(Integer, ForeignKey("handoffs.id"), nullable=False, index=True)
    target_response_time = Column(Integer, nullable=True)  # Minutes
    target_resolution_time = Column(Integer, nullable=True)  # Minutes
    actual_response_time = Column(Integer, nullable=True)  # Minutes
    actual_resolution_time = Column(Integer, nullable=True)  # Minutes
    response_time_breached = Column(Boolean, default=False, nullable=False)
    resolution_time_breached = Column(Boolean, default=False, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


class Escalation(Base):
    """
    Escalation model for tracking conversation escalations.
    """
    __tablename__ = "escalations"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    handoff_id = Column(Integer, ForeignKey("handoffs.id"), nullable=False, index=True)
    from_user_id = Column(Integer, ForeignKey("users.id"), nullable=True)
    to_user_id = Column(Integer, ForeignKey("users.id"), nullable=True)
    reason = Column(Text, nullable=True)
    escalated_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    resolved_at = Column(DateTime, nullable=True)


# ========== NOTIFICATIONS MODELS ==========

class Notification(Base):
    """
    Notification model for in-app notifications.
    """
    __tablename__ = "notifications"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    type = Column(String, nullable=False, index=True)  # new_conversation, lead_captured, system_alert, etc.
    title = Column(String, nullable=False)
    message = Column(Text, nullable=False)
    category = Column(String, nullable=True, index=True)
    is_read = Column(Boolean, default=False, nullable=False, index=True)
    read_at = Column(DateTime, nullable=True)
    action_url = Column(String, nullable=True)  # URL to navigate when clicked
    extra_data = Column(Text, nullable=True)  # JSON string for additional data
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)


class NotificationPreference(Base):
    """
    Notification preference model for user notification settings.
    """
    __tablename__ = "notification_preferences"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    category = Column(String, nullable=False, index=True)  # new_conversation, lead_captured, etc.
    email_enabled = Column(Boolean, default=True, nullable=False)
    in_app_enabled = Column(Boolean, default=True, nullable=False)
    sms_enabled = Column(Boolean, default=False, nullable=False)
    quiet_hours_start = Column(String, nullable=True)  # HH:MM format
    quiet_hours_end = Column(String, nullable=True)  # HH:MM format
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


# ========== SECURITY MODELS ==========

class TwoFactorAuth(Base):
    """
    Two-Factor Authentication model.
    """
    __tablename__ = "two_factor_auth"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), unique=True, nullable=False, index=True)
    secret = Column(String, nullable=False)  # TOTP secret
    is_enabled = Column(Boolean, default=False, nullable=False)
    backup_codes = Column(Text, nullable=True)  # JSON array of backup codes
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


class IPAllowlist(Base):
    """
    IP Allowlist model for restricting access by IP address.
    """
    __tablename__ = "ip_allowlists"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    ip_address = Column(String, nullable=False, index=True)
    description = Column(String, nullable=True)
    is_active = Column(Boolean, default=True, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    created_by_user_id = Column(Integer, ForeignKey("users.id"), nullable=True)


class Session(Base):
    """
    User session model for tracking active sessions.
    """
    __tablename__ = "sessions"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    session_token = Column(String, unique=True, nullable=False, index=True)
    ip_address = Column(String, nullable=True)
    user_agent = Column(String, nullable=True)
    expires_at = Column(DateTime, nullable=False, index=True)
    is_active = Column(Boolean, default=True, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    last_activity = Column(DateTime, default=datetime.utcnow, nullable=False)


class APIKey(Base):
    """
    API Key model for programmatic access.
    """
    __tablename__ = "api_keys"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    name = Column(String, nullable=False)
    key_hash = Column(String, nullable=False, unique=True, index=True)  # Hashed API key
    permissions = Column(Text, nullable=True)  # JSON array of permissions
    last_used_at = Column(DateTime, nullable=True)
    expires_at = Column(DateTime, nullable=True, index=True)
    is_active = Column(Boolean, default=True, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


class AuditLog(Base):
    """
    Audit log model for tracking system events.
    """
    __tablename__ = "audit_logs"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=True, index=True)
    action = Column(String, nullable=False, index=True)  # login, settings_updated, user_created, etc.
    resource_type = Column(String, nullable=True, index=True)  # user, conversation, settings, etc.
    resource_id = Column(Integer, nullable=True)
    ip_address = Column(String, nullable=True)
    user_agent = Column(String, nullable=True)
    details = Column(Text, nullable=True)  # JSON string for additional details
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)


# ========== SALES & PRODUCTS MODELS ==========

class Product(Base):
    """
    Product model for e-commerce.
    """
    __tablename__ = "products"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    name = Column(String, nullable=False, index=True)
    description = Column(Text, nullable=True)
    price = Column(Float, nullable=False)
    currency = Column(String, default="USD", nullable=False)
    category = Column(String, nullable=True, index=True)
    tags = Column(Text, nullable=True)  # JSON array of tags
    image_url = Column(String, nullable=True)
    inventory_count = Column(Integer, nullable=True)  # Nullable for unlimited
    is_active = Column(Boolean, default=True, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


class DigitalAsset(Base):
    """
    Digital asset model for downloadable content.
    """
    __tablename__ = "digital_assets"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    name = Column(String, nullable=False)
    description = Column(Text, nullable=True)
    file_url = Column(String, nullable=False)
    file_size = Column(Integer, nullable=True)  # Bytes
    file_type = Column(String, nullable=True)  # pdf, zip, etc.
    download_count = Column(Integer, default=0, nullable=False)
    is_active = Column(Boolean, default=True, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


class Service(Base):
    """
    Service model for service catalog.
    """
    __tablename__ = "services"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    name = Column(String, nullable=False, index=True)
    description = Column(Text, nullable=True)
    price = Column(Float, nullable=False)
    currency = Column(String, default="USD", nullable=False)
    duration = Column(Integer, nullable=True)  # Minutes
    is_active = Column(Boolean, default=True, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


class Bundle(Base):
    """
    Bundle model for product/service bundles.
    """
    __tablename__ = "bundles"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    name = Column(String, nullable=False, index=True)
    description = Column(Text, nullable=True)
    price = Column(Float, nullable=False)
    currency = Column(String, default="USD", nullable=False)
    discount_percentage = Column(Float, nullable=True)
    product_ids = Column(Text, nullable=True)  # JSON array of product IDs
    service_ids = Column(Text, nullable=True)  # JSON array of service IDs
    is_active = Column(Boolean, default=True, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


class Order(Base):
    """
    Order model for sales transactions.
    """
    __tablename__ = "orders"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    conversation_id = Column(Integer, ForeignKey("conversations.id"), nullable=True, index=True)
    lead_id = Column(Integer, ForeignKey("leads.id"), nullable=True, index=True)
    customer_name = Column(String, nullable=True)
    customer_email = Column(String, nullable=True, index=True)
    customer_phone = Column(String, nullable=True)
    status = Column(String, default="pending", nullable=False, index=True)  # pending, confirmed, shipped, delivered, cancelled
    total_amount = Column(Float, nullable=False)
    currency = Column(String, default="USD", nullable=False)
    payment_status = Column(String, default="pending", nullable=False, index=True)  # pending, paid, refunded
    payment_method = Column(String, nullable=True)
    shipping_address = Column(Text, nullable=True)  # JSON string
    notes = Column(Text, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


class OrderItem(Base):
    """
    Order item model for order line items.
    """
    __tablename__ = "order_items"

    id = Column(Integer, primary_key=True, index=True)
    order_id = Column(Integer, ForeignKey("orders.id"), nullable=False, index=True)
    product_id = Column(Integer, ForeignKey("products.id"), nullable=True)
    service_id = Column(Integer, ForeignKey("services.id"), nullable=True)
    bundle_id = Column(Integer, ForeignKey("bundles.id"), nullable=True)
    item_type = Column(String, nullable=False)  # product, service, bundle
    name = Column(String, nullable=False)
    quantity = Column(Integer, nullable=False)
    unit_price = Column(Float, nullable=False)
    total_price = Column(Float, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)


# ========== ONBOARDING MODELS ==========

class OnboardingStep(Base):
    """
    Onboarding step model for defining onboarding flow.
    """
    __tablename__ = "onboarding_steps"

    id = Column(Integer, primary_key=True, index=True)
    step_key = Column(String, unique=True, nullable=False, index=True)  # welcome, connect_channel, etc.
    title = Column(String, nullable=False)
    description = Column(Text, nullable=True)
    order = Column(Integer, nullable=False)
    is_required = Column(Boolean, default=True, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)


class OnboardingProgress(Base):
    """
    Onboarding progress model for tracking user onboarding.
    """
    __tablename__ = "onboarding_progress"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    step_key = Column(String, nullable=False, index=True)
    is_completed = Column(Boolean, default=False, nullable=False)
    completed_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


# ========== CONVERSATION TAGS & ASSIGNMENTS ==========

class ConversationTag(Base):
    """
    Conversation tag model for categorizing conversations.
    """
    __tablename__ = "conversation_tags"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    name = Column(String, nullable=False, index=True)
    color = Column(String, nullable=True)  # Hex color code for UI
    description = Column(Text, nullable=True)
    created_by_user_id = Column(Integer, ForeignKey("users.id"), nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


class ConversationTagRelation(Base):
    """
    Many-to-many relationship between conversations and tags.
    """
    __tablename__ = "conversation_tag_relations"

    id = Column(Integer, primary_key=True, index=True)
    conversation_id = Column(Integer, ForeignKey("conversations.id"), nullable=False, index=True)
    tag_id = Column(Integer, ForeignKey("conversation_tags.id"), nullable=False, index=True)
    tagged_by_user_id = Column(Integer, ForeignKey("users.id"), nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)


class ConversationAssignment(Base):
    """
    Conversation assignment model for assigning conversations to team members.
    """
    __tablename__ = "conversation_assignments"

    id = Column(Integer, primary_key=True, index=True)
    conversation_id = Column(Integer, ForeignKey("conversations.id"), nullable=False, index=True)
    assigned_to_user_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    assigned_by_user_id = Column(Integer, ForeignKey("users.id"), nullable=True)
    notes = Column(Text, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


# ========== AI RULES & AUTOMATION ==========

class AIRule(Base):
    """
    AI Rule model for intent detection and automated responses.
    
    Stores rule configurations for:
    - Intent detection (greeting, pricing, help, etc.)
    - Keyword matching
    - Automated response templates
    - Priority/ordering
    - Active/inactive status
    """
    __tablename__ = "ai_rules"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    
    # Rule identification
    intent = Column(String, nullable=False, index=True)  # greeting, pricing, help, human, etc.
    name = Column(String, nullable=True)  # Optional friendly name
    description = Column(Text, nullable=True)  # Optional description
    
    # Matching configuration
    keywords = Column(Text, nullable=False)  # JSON array of keywords
    
    # Response configuration
    response = Column(Text, nullable=False)  # Response template
    
    # Rule behavior
    priority = Column(Integer, default=100, nullable=False)  # Lower = higher priority
    is_active = Column(Boolean, default=True, nullable=False)
    
    # Metadata
    created_by_user_id = Column(Integer, ForeignKey("users.id"), nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)
    
    # Statistics (optional)
    trigger_count = Column(Integer, default=0, nullable=False)  # How many times triggered
    last_triggered_at = Column(DateTime, nullable=True)  # Last time triggered


# ========================================
# BILLING & SUBSCRIPTION MODELS
# ========================================

class Plan(Base):
    """Subscription plans (Starter, Business, Pro, Enterprise)."""
    __tablename__ = "plans"
    
    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(50), unique=True, nullable=False)  # "starter", "business", "pro", "enterprise"
    display_name = Column(String(100), nullable=False)  # "Starter Plan"
    description = Column(Text)
    price_monthly = Column(Float, nullable=False)
    price_annual = Column(Float, nullable=False)  # 20% discount
    currency = Column(String(3), default="USD")
    
    # Limits
    conversation_limit = Column(Integer, nullable=False)  # Monthly conversations
    channel_limit = Column(Integer, nullable=False)  # Max channels
    user_limit = Column(Integer, nullable=False)  # Team members
    storage_limit = Column(Integer, nullable=False)  # MB
    ai_tokens_limit = Column(Integer, nullable=True)  # Monthly AI tokens (null = unlimited)
    
    # Features (JSON flags)
    features = Column(Text)  # JSON: {"voice_ai": false, "api_access": false, "crm": false}
    
    # Display
    is_active = Column(Boolean, default=True)
    is_popular = Column(Boolean, default=False)  # Show "Most Popular" badge
    sort_order = Column(Integer, default=0)
    
    # Stripe Product ID
    stripe_product_id = Column(String(255), nullable=True)
    stripe_price_id_monthly = Column(String(255), nullable=True)
    stripe_price_id_annual = Column(String(255), nullable=True)
    
    # Metadata
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Relationships
    subscriptions = relationship("Subscription", back_populates="plan")


class Subscription(Base):
    """User/Business subscriptions."""
    __tablename__ = "subscriptions"
    
    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    plan_id = Column(Integer, ForeignKey("plans.id"), nullable=False)
    
    # Stripe data
    stripe_subscription_id = Column(String(255), unique=True, index=True)
    stripe_customer_id = Column(String(255), index=True)
    
    # Status
    status = Column(String(20), default="active")  # active, past_due, canceled, trialing, incomplete, paused
    billing_cycle = Column(String(10), default="monthly")  # monthly, annual
    
    # Dates
    current_period_start = Column(DateTime)
    current_period_end = Column(DateTime)
    trial_start = Column(DateTime)
    trial_end = Column(DateTime)
    canceled_at = Column(DateTime)
    ended_at = Column(DateTime)
    
    # Pricing
    amount = Column(Float, nullable=False)
    currency = Column(String(3), default="USD")
    
    # Cancel settings
    cancel_at_period_end = Column(Boolean, default=False)
    cancellation_reason = Column(Text)
    
    # Metadata
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Relationships
    business = relationship("Business", back_populates="subscription")
    plan = relationship("Plan", back_populates="subscriptions")
    invoices = relationship("Invoice", back_populates="subscription")
    usage_records = relationship("UsageRecord", back_populates="subscription")
    addons = relationship("SubscriptionAddon", back_populates="subscription")


class Invoice(Base):
    """Billing invoices."""
    __tablename__ = "invoices"
    
    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    subscription_id = Column(Integer, ForeignKey("subscriptions.id"), nullable=True)
    
    # Invoice details
    invoice_number = Column(String(50), unique=True, nullable=False, index=True)
    stripe_invoice_id = Column(String(255), unique=True, index=True)
    
    # Amounts
    subtotal = Column(Float, nullable=False)
    tax = Column(Float, default=0.0)
    total = Column(Float, nullable=False)
    currency = Column(String(3), default="USD")
    
    # Status
    status = Column(String(20), default="draft")  # draft, open, paid, void, uncollectible
    paid_at = Column(DateTime)
    
    # Dates
    invoice_date = Column(DateTime, default=datetime.utcnow)
    due_date = Column(DateTime)
    period_start = Column(DateTime)
    period_end = Column(DateTime)
    
    # Payment
    payment_id = Column(Integer, ForeignKey("payments.id"), nullable=True)
    
    # PDF
    pdf_url = Column(String(500))
    
    # Metadata
    notes = Column(Text)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Relationships
    business = relationship("Business", back_populates="invoices")
    subscription = relationship("Subscription", back_populates="invoices")
    payment = relationship("Payment", back_populates="invoice", uselist=False, foreign_keys="[Invoice.payment_id]")
    line_items = relationship("InvoiceLineItem", back_populates="invoice")


class InvoiceLineItem(Base):
    """Invoice line items."""
    __tablename__ = "invoice_line_items"
    
    id = Column(Integer, primary_key=True, index=True)
    invoice_id = Column(Integer, ForeignKey("invoices.id"), nullable=False, index=True)
    
    description = Column(String(500), nullable=False)
    quantity = Column(Integer, default=1)
    unit_price = Column(Float, nullable=False)
    amount = Column(Float, nullable=False)
    
    # Type: subscription, addon, overage, etc.
    item_type = Column(String(50))
    
    # Metadata
    created_at = Column(DateTime, default=datetime.utcnow)
    
    # Relationships
    invoice = relationship("Invoice", back_populates="line_items")


class Payment(Base):
    """Payment transactions."""
    __tablename__ = "payments"
    
    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    invoice_id = Column(Integer, ForeignKey("invoices.id"), nullable=True)
    
    # Payment details
    stripe_payment_intent_id = Column(String(255), unique=True, index=True)
    amount = Column(Float, nullable=False)
    currency = Column(String(3), default="USD")
    
    # Status
    status = Column(String(20), default="pending")  # pending, succeeded, failed, canceled, refunded
    
    # Payment method
    payment_method_id = Column(Integer, ForeignKey("payment_methods.id"), nullable=True)
    payment_method_type = Column(String(50))  # card, bank_transfer, etc.
    
    # Metadata
    failure_reason = Column(Text)
    receipt_url = Column(String(500))
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Relationships
    business = relationship("Business", back_populates="payments")
    invoice = relationship("Invoice", back_populates="payment", foreign_keys="[Payment.invoice_id]")
    payment_method = relationship("PaymentMethod", back_populates="payments")


class PaymentMethod(Base):
    """Saved payment methods (cards, etc.)."""
    __tablename__ = "payment_methods"
    
    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    
    # Stripe data
    stripe_payment_method_id = Column(String(255), unique=True, index=True)
    
    # Card details (last 4, brand, etc.)
    type = Column(String(20), default="card")  # card, bank_account, etc.
    card_brand = Column(String(20))  # visa, mastercard, etc.
    card_last4 = Column(String(4))
    card_exp_month = Column(Integer)
    card_exp_year = Column(Integer)
    
    # Status
    is_default = Column(Boolean, default=False)
    is_active = Column(Boolean, default=True)
    
    # Metadata
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Relationships
    business = relationship("Business", back_populates="payment_methods")
    payments = relationship("Payment", back_populates="payment_method")


class UsageRecord(Base):
    """Track usage for billing (conversations, AI tokens, storage)."""
    __tablename__ = "usage_records"
    
    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    subscription_id = Column(Integer, ForeignKey("subscriptions.id"), nullable=False)
    
    # Usage type
    resource_type = Column(String(50), nullable=False, index=True)  # conversation, ai_token, storage, channel, user
    quantity = Column(Integer, nullable=False)
    
    # Period
    period_start = Column(DateTime, nullable=False)
    period_end = Column(DateTime, nullable=False)
    
    # Metadata (renamed to avoid SQLAlchemy reserved word)
    resource_metadata = Column(Text)  # JSON: Additional context
    created_at = Column(DateTime, default=datetime.utcnow)
    
    # Relationships
    business = relationship("Business", back_populates="usage_records")
    subscription = relationship("Subscription", back_populates="usage_records")


class Addon(Base):
    """Available add-ons (Voice AI, CRM, etc.)."""
    __tablename__ = "addons"
    
    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(100), unique=True, nullable=False)  # "voice_ai"
    display_name = Column(String(100), nullable=False)  # "Voice AI Module"
    description = Column(Text)
    
    # Pricing
    price_monthly = Column(Float, nullable=False)
    currency = Column(String(3), default="USD")
    
    # Display
    icon = Column(String(50))  # lucide icon name: "mic", "image", etc.
    image_url = Column(String(500))
    color = Column(String(20))  # Tailwind color class
    
    # Status
    is_active = Column(Boolean, default=True)
    sort_order = Column(Integer, default=0)
    
    # Features this addon provides
    features = Column(Text)  # JSON: {"voice_ai": true, "image_recognition": true}
    
    # Stripe Product ID
    stripe_product_id = Column(String(255), nullable=True)
    stripe_price_id = Column(String(255), nullable=True)
    
    # Metadata
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Relationships
    subscriptions = relationship("SubscriptionAddon", back_populates="addon")


class SubscriptionAddon(Base):
    """User's active add-ons."""
    __tablename__ = "subscription_addons"
    
    id = Column(Integer, primary_key=True, index=True)
    subscription_id = Column(Integer, ForeignKey("subscriptions.id"), nullable=False, index=True)
    addon_id = Column(Integer, ForeignKey("addons.id"), nullable=False)
    
    # Stripe Subscription Item ID
    stripe_subscription_item_id = Column(String(255), nullable=True)
    
    # Status
    is_active = Column(Boolean, default=True)
    
    # Dates
    started_at = Column(DateTime, default=datetime.utcnow)
    canceled_at = Column(DateTime)
    
    # Metadata
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Relationships
    subscription = relationship("Subscription", back_populates="addons")
    addon = relationship("Addon", back_populates="subscriptions")


class BillingEvent(Base):
    """Audit log for billing events."""
    __tablename__ = "billing_events"
    
    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=True)
    
    # Event details
    event_type = Column(String(50), nullable=False, index=True)  # subscription_created, payment_failed, etc.
    description = Column(Text)
    
    # Metadata (renamed to avoid SQLAlchemy reserved word)
    event_metadata = Column(Text)  # JSON
    created_at = Column(DateTime, default=datetime.utcnow)
    
    # Relationships
    business = relationship("Business", back_populates="billing_events")
    user = relationship("User", back_populates="billing_events")


# ========== PERFORMANCE INDEXES ==========
# Composite indexes for frequently queried column combinations
# These dramatically improve query performance for dashboard and filtering

# Conversations - composite indexes for common query patterns
Index('idx_conversations_business_created', Conversation.business_id, Conversation.created_at)
Index('idx_conversations_business_intent', Conversation.business_id, Conversation.intent)
Index('idx_conversations_business_channel', Conversation.business_id, Conversation.channel)
Index('idx_conversations_user_channel', Conversation.user_id, Conversation.channel)

# Messages - composite indexes
Index('idx_messages_business_created', Message.business_id, Message.created_at)
Index('idx_messages_conversation_created', Message.conversation_id, Message.created_at)
Index('idx_messages_user_channel', Message.user_id, Message.channel)

# Leads - composite indexes for filtering and reporting
Index('idx_leads_business_status', Lead.business_id, Lead.status)
Index('idx_leads_business_created', Lead.business_id, Lead.created_at)
Index('idx_leads_status_created', Lead.status, Lead.created_at)

# Knowledge entries - for RAG queries
Index('idx_knowledge_business_active', KnowledgeEntry.business_id, KnowledgeEntry.is_active)
Index('idx_knowledge_business_intent', KnowledgeEntry.business_id, KnowledgeEntry.intent)

# Conversation memory - for AI context retrieval
Index('idx_memory_user_channel', ConversationMemory.user_id, ConversationMemory.channel)
Index('idx_memory_business_updated', ConversationMemory.business_id, ConversationMemory.updated_at)

# Analytics events - for dashboard aggregations
Index('idx_analytics_business_type_created', AnalyticsEvent.business_id, AnalyticsEvent.event_type, AnalyticsEvent.created_at)
Index('idx_analytics_channel_created', AnalyticsEvent.channel, AnalyticsEvent.created_at)

# Handoffs - for queue management
Index('idx_handoffs_business_status', Handoff.business_id, Handoff.status)
Index('idx_handoffs_business_priority', Handoff.business_id, Handoff.priority)
Index('idx_handoffs_assigned_status', Handoff.assigned_to_user_id, Handoff.status)

# Notifications - for user inbox
Index('idx_notifications_user_isread', Notification.user_id, Notification.is_read)
Index('idx_notifications_user_created', Notification.user_id, Notification.created_at)

# Orders - for sales reporting
Index('idx_orders_business_status', Order.business_id, Order.status)
Index('idx_orders_business_created', Order.business_id, Order.created_at)
Index('idx_orders_business_payment', Order.business_id, Order.payment_status)

# Products - for catalog queries
Index('idx_products_business_active', Product.business_id, Product.is_active)
Index('idx_products_business_category', Product.business_id, Product.category)

# Services - for service catalog
Index('idx_services_business_active', Service.business_id, Service.is_active)

# AI Rules - for intent matching
Index('idx_airules_business_active', AIRule.business_id, AIRule.is_active)
Index('idx_airules_business_intent', AIRule.business_id, AIRule.intent)
Index('idx_airules_business_priority', AIRule.business_id, AIRule.priority)

# Channel Integrations - for webhook routing
Index('idx_integrations_channel_active', ChannelIntegration.channel, ChannelIntegration.is_active)
Index('idx_integrations_business_channel', ChannelIntegration.business_id, ChannelIntegration.channel)

# Ad Assets - for ad studio
Index('idx_adassets_business_status', AdAsset.business_id, AdAsset.status)

# Audit logs - for security reviews
Index('idx_audit_business_action', AuditLog.business_id, AuditLog.action)
Index('idx_audit_user_created', AuditLog.user_id, AuditLog.created_at)

# API Keys - for auth
Index('idx_apikeys_business_active', APIKey.business_id, APIKey.is_active)

# Sessions - for active session lookup
Index('idx_sessions_user_active', Session.user_id, Session.is_active)
Index('idx_sessions_expires_active', Session.expires_at, Session.is_active)

# Billing - for subscription management and reporting
Index('idx_subscriptions_business_status', Subscription.business_id, Subscription.status)
Index('idx_subscriptions_stripe', Subscription.stripe_subscription_id)
Index('idx_invoices_business_status', Invoice.business_id, Invoice.status)
Index('idx_invoices_stripe', Invoice.stripe_invoice_id)
Index('idx_payments_business_status', Payment.business_id, Payment.status)
Index('idx_usage_business_type_period', UsageRecord.business_id, UsageRecord.resource_type, UsageRecord.period_start)
Index('idx_billing_events_business_type', BillingEvent.business_id, BillingEvent.event_type)

